/**
 * NeuroFrame — the standardized neural feedback frame used by the runtime.
 *
 * It is NOT raw EEG data. It represents interpreted and normalized feedback
 * from upstream EEG / BCI processing.
 *
 * This is the SINGLE canonical definition shared by all modules:
 *   - runtime / LevelController (同学 C)
 *   - bci / MockNeuroSource & BridgeNeuroSource (同学 D)
 *   - telemetry / TelemetrySystem (同学 D)
 *
 * Based on spec Section 5 (NeuroFrame 标准化契约).
 */

export type NeuroSource = "mock" | "bridge";

export type SignalQuality = "good" | "poor" | "lost" | "unknown";

export interface NeuroFrame {
  /** Monotonic timestamp generated by runtime when the frame is accepted. */
  timestampMs: number;

  /** Data source. */
  source: NeuroSource;

  /**
   * Standardized attention score, 0-1.
   *
   * - `null` means no attention estimate is currently available.
   * - `null` must NOT be interpreted as "distracted" or "low attention."
   */
  attention: number | null;

  /** Signal state. Lost signal must not be treated as low attention. */
  signalQuality: SignalQuality;

  /** Optional confidence of the attention estimate, 0-1. */
  confidence?: number;

  /** Optional target frequency response, e.g. 15Hz response. */
  targetPower?: number;

  /** Optional distractor frequency response, e.g. 20Hz response. */
  distractorPower?: number;

  /** Development-only raw payload. Must not be required by level logic. */
  raw?: unknown;
}

/**
 * NeuroSourceClient — abstraction over a data source that emits NeuroFrames.
 *
 * Spec Section 5.3: `subscribe()` returns an unsubscribe function.
 */
export interface NeuroSourceClient {
  start(): void;
  stop(): void;
  subscribe(listener: (frame: NeuroFrame) => void): () => void;
}

/**
 * Clamp a number into the [0, 1] range.
 */
export function clamp01(value: number): number {
  return Math.max(0, Math.min(1, value));
}

/**
 * Check whether a NeuroFrame can be used by closed-loop logic.
 *
 * Contract rule (Section 5.2):
 * - Only when `signalQuality === "good"` AND `attention` is a number (non-null)
 *   can we use it to drive bloomProgress.
 * - "lost" and "unknown" must not be treated as low attention.
 */
export function isUsableNeuroFrame(frame: NeuroFrame): boolean {
  return frame.signalQuality === "good" && frame.attention !== null;
}

/**
 * Normalize a possibly unsafe frame into valid semantic ranges.
 *
 * Contract rules:
 * - attention=null must remain null (never converted to 0)
 * - confidence is clamped only if provided
 * - attention/confidence numbers are clamped into [0, 1]
 */
export function normalizeNeuroFrame(frame: NeuroFrame): NeuroFrame {
  return {
    ...frame,
    attention:
      frame.attention === null ? null : clamp01(frame.attention),
    confidence:
      frame.confidence === undefined ? undefined : clamp01(frame.confidence),
  };
}
